#! /bin/bash
#
# Elasticsearch build script
#
# Author: Steve Chaplin
#
# Date: 18-11-2016
#
# Purpose: Build the Elasticsearch environment
#
# Usage: build destdir
#
####################################################################################################
# Files to ship.
#
SHIP_FILES=( Dockerfile )
#
####################################################################################################
# Include convenience functions.
#
. ../ci_scripts/common
#
####################################################################################################
# Configuration.
#
BUILD_DIR="$BUILD_DIR/Elasticsearch"
#
####################################################################################################
# Ship into the staging area.
#
ship SHIP_FILES[@] $BUILD_DIR
#
####################################################################################################
exit 0
