#
# Docker file to build the Kibana environment based on Image provided by Elastic
#
####################################################################################################
#
#
FROM docker.elastic.co/kibana/kibana:5.3.0
#
#
####################################################################################################
#
# Set the default command.
#
# ENTRYPOINT inherited from original Image
#
####################################################################################################
