#! /bin/bash

# Copyright (C) 2017 e-ito Technology Services GmbH
# e-mail: info@e-ito.de

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#
# Logstash build script
#
####################################################################################################
# Files to ship.
#
SHIP_FILES=( filesystem \
			 Dockerfile )
#
####################################################################################################
# Include convenience functions.
#
. ../ci_scripts/common
#
####################################################################################################
# Configuration.
#
BUILD_DIR="$BUILD_DIR/Logstash"
#
####################################################################################################
# Ship into the staging area.
#
ship SHIP_FILES[@] $BUILD_DIR
#
####################################################################################################
exit 0
