#
# Docker file to build the Elasticsearch environment based on Image provided by Elastic
#
####################################################################################################
#
#
FROM docker.elastic.co/logstash/logstash:5.3.0
#
ADD filesystem /
#
#
####################################################################################################
#
# Set the default command.
#
# ENTRYPOINT inherited from original Image
#
####################################################################################################
